# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy FastAPI App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy FastAPI App to Azure Web App
        run: |
          az webapp up --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --runtime "PYTHON|3.10"
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          VECTOR_STORE_ID: ${{ secrets.VECTOR_STORE_ID }}
          AZURE_ASSISTANT_ID: ${{ secrets.AZURE_ASSISTANT_ID }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Notify on Success
        if: success()
        run: echo "✅ FastAPI App successfully deployed to Azure!"
